In [3]:
import pandas as pd
import numpy as np
import os

In [8]:
df = pd.read_csv('df_apple.csv')
df

,Product_ID,Product_Type,Model,Release_Date,Price,In_Stock,Category_Type
0,1,MacBook,"MacBook Pro 13""",2021-05-21,1299.99,True,desktop
1,2,iPad,iPad Air,2022-03-18,599.99,False,mobile
2,3,iPhone,iPhone 13,2023-09-24,999.99,True,mobile
3,4,Watch,Watch Series 7,2021-10-15,399.99,True,wearable
4,5,AirPods,AirPods Pro,2021-05-18,249.99,False,wearable
5,6,MacMini,NaN,NaN,699.99,True,desktop
6,7,NaN,MacMini M1,2020-11-17,NaN,False,desktop
7,8,MacBook Air,MacBook Air M1,2020-12-22,999.99,NaN,desktop

In [1]:
# ----------expanding

# How would you calculate the expanding sum of the Price column, creating a new column that shows the cumulative total price for each row?
# Can you demonstrate how to compute an expanding average of the Price and add it as a new column in the DataFrame?
# How would you use expanding to determine the maximum Price encountered so far for each product as you go down the rows?
# Is it possible to create a new column showing the expanding minimum value of the Product_ID as you move through the DataFrame?
# Can you use expanding with a custom function to count the number of True values in the In_Stock column cumulatively?
# How would you apply an expanding operation to calculate the standard deviation of Price up to the current row?
# Can you show how to use expanding to create a new column that reflects the cumulative number of unique Product_Type values encountered so far?
# How would you use an expanding window to calculate the cumulative count of products in each Category_Type?
# Is there a way to apply an expanding function that concatenates the Model names as a new column, adding each model to the string as you go down the rows?
# Can you create a column that uses expanding to maintain a running list of all Release_Dates encountered up to the current row?

In [3]:
# ----------interpolate

# How would you use interpolate to fill missing Price values in the DataFrame?
# Can you demonstrate how to apply linear interpolation to fill NaN values in the Price column?
# How would you use interpolate with a backward fill method to handle NaN values in the Price column?
# Is there a way to apply interpolate with a polynomial method (e.g., quadratic) to estimate missing Price values?
# How can you use the interpolate method to fill missing values in a time series, specifically in the Release_Date column?
# Can you interpolate missing values in the Price column while limiting the maximum gap filled to 2 consecutive NaNs?
# How would you use interpolate to fill NaN values in the Price column only if they occur after a non-NaN value?
# Is it possible to use the interpolate method with a spline order (e.g., cubic) to fill the missing values in the Price column?
# How can you apply the interpolate method to simultaneously fill missing values in both Price and another numeric column (if it existed) in the DataFrame?
# Can you demonstrate how to use interpolate with a seasonal adjustment, assuming the Price fluctuates with a known seasonality pattern?