In [2]:
# lambda
# map
# filter 
# reduce
# apply
# applyMap

In [3]:
import pandas as pd
import numpy as np
import os

In [8]:
df = pd.read_csv('df_apple.csv')
df

,Product_ID,Product_Type,Model,Release_Date,Price,In_Stock,Category_Type
0,1,MacBook,"MacBook Pro 13""",2021-05-21,1299.99,True,desktop
1,2,iPad,iPad Air,2022-03-18,599.99,False,mobile
2,3,iPhone,iPhone 13,2023-09-24,999.99,True,mobile
3,4,Watch,Watch Series 7,2021-10-15,399.99,True,wearable
4,5,AirPods,AirPods Pro,2021-05-18,249.99,False,wearable
5,6,MacMini,NaN,NaN,699.99,True,desktop
6,7,NaN,MacMini M1,2020-11-17,NaN,False,desktop
7,8,MacBook Air,MacBook Air M1,2020-12-22,999.99,NaN,desktop

In [4]:
# -------------lambda

# How can you use a lambda function to create a new column called 'Discounted_Price' that applies a 10% discount to the 'Price' column for all products?
# Is it possible to use a lambda function with the apply method to extract the year from the 'Release_Date' column and create a new column called 'Release_Year'?
# How would you use a lambda function to filter the DataFrame and keep only the rows where the 'Category_Type' is 'wearable'?
# Can you demonstrate using a lambda function to calculate the total price of all products that are 'In_Stock'?
# How can you apply a lambda function to create a new column 'Product_Length' that extracts the numeric value from the 'Model' column for products with a model description (e.g., 'MacBook Pro 13"')?

In [6]:
# -------------map

# How can you use the map function to create a new column called 'Product_Type_Length' that calculates the length of the 'Product_Type' strings for all products?
# Is it possible to use the map function to convert the 'In_Stock' column values (True/False) to 'Available' and 'Out of Stock' respectively in a new column called 'Availability'?
# How would you use the map function to round the 'Price' column to the nearest hundred and store the rounded values in a new column 'Rounded_Price'?
# Can you demonstrate using the map function to convert the 'Category_Type' column values to lowercase for consistency in a new column called 'category'?
# How can you apply the map function to create a new column 'Product_Age' that calculates the number of years since the 'Release_Date' for each product?

In [9]:
# ------------filter

# How can you use the filter function to select only the rows where the 'Price' is greater than $500 and the 'In_Stock' is True?
# Is it possible to use the filter function to select rows where the 'Product_Type' contains the word 'Mac'?
# How would you use the filter function to select rows where the 'Category_Type' is either 'desktop' or 'wearable'?
# Can you demonstrate using the filter function to select rows where the 'Release_Date' is in the year 2021?
# How can you apply the filter function to select rows where the 'Model' column is not NaN (missing values)?

In [11]:
# ------------reduce

# How can you use the reduce function to find the maximum price among all the products in the DataFrame?
# Is it possible to use the reduce function to calculate the total sum of prices for all products that are 'In_Stock'?
# How would you use the reduce function to find the product with the earliest 'Release_Date'?
# Can you demonstrate using the reduce function to concatenate all the 'Product_Type' values into a single string separated by commas?
# How can you apply the reduce function to find the average price of all products in the DataFrame?

In [12]:
# ------------apply

# How can you use the apply function to create a new column 'Discounted_Price' that applies a 10% discount to the 'Price' column for all products?
# Is it possible to use the apply function with a custom function to extract the year from the 'Release_Date' column and create a new column called 'Release_Year'?
# How would you use the apply function to filter the DataFrame and keep only the rows where the 'Category_Type' is 'wearable'?
# Can you demonstrate using the apply function to calculate the total price of all products that are 'In_Stock'?
# How can you apply the apply function to create a new column 'Product_Length' that extracts the numeric value from the 'Model' column for products with a model description (e.g., 'MacBook Pro 13"')?

In [13]:
# ------------applyMap


# How can you use the applymap function to convert all the 'Price' values to a different currency format (e.g., from dollars to euros)?
# Is it possible to use the applymap function to format all the 'Release_Date' values in a different date format (e.g., from 'yyyy-mm-dd' to 'dd/mm/yyyy')?
# How would you use the applymap function to convert all the 'In_Stock' values (True/False) to 'Yes' and 'No' strings?
# Can you demonstrate using the applymap function to apply a custom function to all numeric values in the DataFrame to round them to the nearest integer?
# How can you apply the applymap function to convert all the 'Product_Type' values to uppercase?