In [3]:
import pandas as pd
import numpy as np
import os

In [8]:
df = pd.read_csv('df_apple.csv')
df

,Product_ID,Product_Type,Model,Release_Date,Price,In_Stock,Category_Type
0,1,MacBook,"MacBook Pro 13""",2021-05-21,1299.99,True,desktop
1,2,iPad,iPad Air,2022-03-18,599.99,False,mobile
2,3,iPhone,iPhone 13,2023-09-24,999.99,True,mobile
3,4,Watch,Watch Series 7,2021-10-15,399.99,True,wearable
4,5,AirPods,AirPods Pro,2021-05-18,249.99,False,wearable
5,6,MacMini,NaN,NaN,699.99,True,desktop
6,7,NaN,MacMini M1,2020-11-17,NaN,False,desktop
7,8,MacBook Air,MacBook Air M1,2020-12-22,999.99,NaN,desktop

In [1]:
#--------qcut

# Using the qcut function, divide the "Price" column into 3 equal-sized bins. What are the price ranges for each bin?
# Apply qcut to the "Release_Date" column to create 4 bins of equal frequency. What are the date ranges for each bin?
# How many products fall into each of the 4 bins when you use qcut on the "Price" column to ensure equal frequencies?
# Apply qcut to the "Product_ID" column to create 2 bins with equal frequencies. What are the product ID ranges for each bin?
# Calculate the mean price for each bin created by qcut on the "Price" column.

In [2]:
#--------quantile

# Calculate the 25th percentile (1st quartile) of the "Price" column using the quantile function.
# Determine the 75th percentile (3rd quartile) of the "Price" column using the quantile function.
# Find the median (50th percentile) of the "Release_Date" column using the quantile function.
# Calculate the 10th percentile of the "Product_ID" column using the quantile function.
# Determine the 90th percentile of the "Product_ID" column using the quantile function.